//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoClubManager.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoClubManager.Local.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string txtAdd {
            get {
                return ResourceManager.GetString("txtAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string txtAddress {
            get {
                return ResourceManager.GetString("txtAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Club Manager.
        /// </summary>
        public static string txtAppName {
            get {
                return ResourceManager.GetString("txtAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string txtCancel {
            get {
                return ResourceManager.GetString("txtCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Rental.
        /// </summary>
        public static string txtDateOfRental {
            get {
                return ResourceManager.GetString("txtDateOfRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string txtDue {
            get {
                return ResourceManager.GetString("txtDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string txtDueDate {
            get {
                return ResourceManager.GetString("txtDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-mail.
        /// </summary>
        public static string txtEmail {
            get {
                return ResourceManager.GetString("txtEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By:.
        /// </summary>
        public static string txtFilterBy {
            get {
                return ResourceManager.GetString("txtFilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Rent.
        /// </summary>
        public static string txtForRent {
            get {
                return ResourceManager.GetString("txtForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued to.
        /// </summary>
        public static string txtIssuedTo {
            get {
                return ResourceManager.GetString("txtIssuedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        public static string txtMovie {
            get {
                return ResourceManager.GetString("txtMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rental.
        /// </summary>
        public static string txtNewRental {
            get {
                return ResourceManager.GetString("txtNewRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string txtOk {
            get {
                return ResourceManager.GetString("txtOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string txtPhoneNum {
            get {
                return ResourceManager.GetString("txtPhoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string txtRemove {
            get {
                return ResourceManager.GetString("txtRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string txtRent {
            get {
                return ResourceManager.GetString("txtRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental is not allowed. User must return all rented movies before making a new rental..
        /// </summary>
        public static string txtRentalNotAllowed {
            get {
                return ResourceManager.GetString("txtRentalNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rented.
        /// </summary>
        public static string txtRented {
            get {
                return ResourceManager.GetString("txtRented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Filters.
        /// </summary>
        public static string txtResetFilters {
            get {
                return ResourceManager.GetString("txtResetFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string txtReturn {
            get {
                return ResourceManager.GetString("txtReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string txtUserName {
            get {
                return ResourceManager.GetString("txtUserName", resourceCulture);
            }
        }
    }
}
